### ISSUE TITLE
Loading players

### ISSUE THREAD

**Issue by mfw78** [rndlabs/monSI#5]
Implement `getLogs` method on `StakeRegistry` to load all players. Replay:

* `StakeUpdated` for adding amounts to stake.
* `StakeSlashed` for remove amounts from stake.

Additionally, we should include a `stakeAmount` for the `Player` to track this value and any subsequent slashes / updates.

**Comment by ldeffenb** [comment]
I just implemented a Player.stake element and have it displaying in the All Players and Round Players boxes.   Unfortunately, the StakeSlashed events need to be processed in sequence with the StakeUpdated.   The StakeUpdated event SETS the state to an amount while the StakeSlashed event SUBTRACTS the amount from the current stake not allowing it to go negative.

I don't know how to get the pair logs from the StakeRegistry interleaved in time rather than individually monitored.   And the monitor will need to look at the state RUNNING before processing them, I think, maybe, see the next comment.

The initial sync also needs to filter both events and process them in time sequence, stopping at the starting block.   But if we stop at the starting block and the monitor waits for RUNNING, then we'll potentially have a gap of events that we miss while the blocks are loading.   Seems maybe the stakes would need to have a separate state for starting to process the events, but that might get messed up if a slash log comes in from a winner event.   I think the stakes will need to only look at the stake contract, and ignore the slashes from the redistributor.  (Yes, I probably have those contract names not quite right).

**Comment by ldeffenb** [comment]
@mfw78  If you can work out the proper filter for both the initial load and a single, time-sequenced subscribe, it would be appreciated.  I'm out of my depth when it comes to more than a single filter term.

Possibly related to #10
